### ISSUE TITLE
feature request: open result from https://filmfans.org/

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#186] opened 2023-08-25 21:36 UTC
when I search for a movie with this script is a movie is on https://filmfans.org/ and it is found when I click on icon it open the homepage of it and not the result.
but when I checked the response in console of firefox I see this:

```
https://filmfans.org/api/v2/search?q=tt7897478
{
    "counterPartIs": "serienfans.org",
    "result": [
        {
            "description": "Explosiver Action-Thriller über eine Flugzeugentführung durch islamistische Terroristen. Zwei Piloten werden auf eine gefährliche humanitäre Mission geschickt: Sie sollen Zivilisten aus der von dem IS umzingelten Stadt Palmyra ausfliegen. Während des Fluges gelingt es jedoch Dschihadisten, die Maschine in ihre Gewalt zu bringen. Es droht ein grausamer Selbstmordanschlag mit tausenden Opfern.",
            "image": [
                {
                    "media_url": "/media/457758064057/70/105"
                }
            ],
            "title": "Damascus Under Fire",
            "url_id": "damascus-time",
            "year": 2018
        }
    ],
    "resultCounterPart": [
    ]
}
```

and on that website the url of movie is https://filmfans.org/damascus-time which is https://filmfans.org/url_id with url_id returned in response of script.

can this be implemented?
is it even possible for this script in its current form to create this url from response?

**Comment by Purfview** [comment] 2023-08-25 21:47
Dupe of: https://github.com/Purfview/IMDb-Scout-Mod/issues/97

**Closed by Purfview** 2023-08-25 21:47 UTC
