### ISSUE TITLE
Compatability with Firemonkey

### ISSUE THREAD

**Issue by Dodge100** [Purfview/IMDb-Scout-Mod#225] opened 2024-07-15 15:49 UTC
are there any plans to integrate Firemonkey support? currently, i am unable to use it on firemonkey.

**Comment by Purfview** [comment] 2024-07-15 15:51
Dupe of https://github.com/Purfview/IMDb-Scout-Mod/issues/180

**Closed by Purfview** 2024-07-15 15:51 UTC

**Comment by Dodge100** [comment] 2024-07-15 15:54
oh that's mb, i just search for compatability 💀.
