### ISSUE TITLE
RARBG not working correctly 

### ISSUE THREAD

**Issue by Xazmah** [Purfview/IMDb-Scout-Mod#24] opened 2021-02-11 17:14 UTC
Always reporting that no results are found, even when results exist

**Comment by Purfview** [comment] 2021-02-11 18:01
Can't reproduce, works OK on my end. 
Post IMDb ID and paste the page source of rarbg to paste.bin.

**Comment by Xazmah** [comment] 2021-02-11 23:35
IMDb: https://i.imgur.com/S9UnYiH.png
RARBG: https://i.imgur.com/OfATKB2.png

**Comment by Purfview** [comment] 2021-02-11 23:47
I didn't asked for screenshots, they don't tell me anything.

**Comment by Xazmah** [comment] 2021-02-12 19:05
IMDb ID: tt0111161
page source: https://paste.ee/p/XYnZe

**Comment by Xazmah** [comment] 2021-02-12 19:10
Changed the url from rarbgweb.org to rarbgenter.org (the mirror that the official website rarbg.to redirect to) and it's working fine now

**Comment by Purfview** [comment] 2021-02-12 20:39
Should be fixed in v8.7.4.

That mirror is blocked on every isp I tried.

**Comment by Xazmah** [comment] 2021-02-12 20:48
Working fine now

**Closed** 2021-02-12 21:13 UTC
