### ISSUE TITLE
Doesn't work with Radarr version 4.0.0.5241 (nightly) 

### ISSUE THREAD

**Issue by plsharevme** [Purfview/IMDb-Scout-Mod#79] opened 2021-09-01 09:34 UTC
it show add successful undefined , but at my radarr no found the movie.

my root folder is /data/media/movies/english

**Comment by Purfview** [comment] 2021-09-01 13:37
Post your Radarr version and imdb id of the movie.

**Comment by plsharevme** [comment] 2021-09-02 02:42
radarr version 4.0.0.5241 (nightly)

all movie cannot add from imdb.

**Comment by Purfview** [comment] 2021-09-02 03:21
That is alpha version, you should ask Radarr why v4 doesn't support pre-v3 API or will it be added.

I've no idea how they differs, or will everything work as intended in v3 API, nor why I didn't used v3 API urls in the first place.
I just changed urls to v3 API (`/api/movie/` to `/api/v3/movie/`): https://github.com/Purfview/IMDb-Scout-Mod/tree/Test-v3-API

Test if everything works there as intended, try to add existing movies, check indicating colors ect..

**Comment by Purfview** [comment] 2021-09-02 06:06
This issue nor fix is for sonarr... did you tested on your Radarr?

**Comment by plsharevme** [comment] 2021-09-02 06:10
just tested on radarr , it also came out undefined.

my radarr okay if import by list or by ombi

**Comment by Purfview** [comment] 2021-09-02 06:11
You mean that you tested that new branch I posted?

**Comment by plsharevme** [comment] 2021-09-02 06:20
https://github.com/Purfview/IMDb-Scout-Mod/blob/Test-v3-API/IMDb_Scout_Mod.user.js

this script? drag to extension or copy all paste to new script violet monkey? the old script uninstall 1st ?

**Comment by Purfview** [comment] 2021-09-02 06:25
Yes this one. Press on 'Raw' there and monkey should install it. No need to uninstall anything.
I've no idea what "greafox" ir.

**Comment by plsharevme** [comment] 2021-09-02 06:34
yup, after click on raw popup and installed, also same result .

> I've no idea what "greafox" is.
sorry is 
https://greasyfork.org/

**Comment by Purfview** [comment] 2021-09-02 06:40
Did you refreshed imdb page after install?
Look at the script in your monkey, at line 6774 there should be "/api/v3/movie", so you'll know that you've installed the right script.

**Comment by plsharevme** [comment] 2021-09-02 06:43
yup , have install right script , nightly is use v3 ? 

    method: "GET",
    url: radarr_url + "/api/v3/movie",
    headers: {
      "X-Api-Key": radarr_apikey,
      "Accept": "text/json"
    },
    onload: function(response) {
      let responseJSON = null;

**Comment by Purfview** [comment] 2021-09-02 08:04
Then I dunno what's up with that nightly, you should ask at Radarr's places.
Latest stable is v3.2.2.5080 https://github.com/Radarr/Radarr/releases
I've no time to look at alpha versions nor support different versions if they are incompatible.

> nightly is use v3 ?

I think so.

**Comment by plsharevme** [comment] 2021-09-02 08:12
okay, thanks for your effort and such great script !!

**Comment by Purfview** [comment] 2022-02-14 22:36
Should be fixed in v15.2.

**Closed by Purfview** 2022-02-14 22:36 UTC
